In [1]:
import pandas as pd
import numpy as np

In [2]:
frame = pd.read_csv('./bitflyerJPY_1-min_data_2017-07-04_to_2018-06-27.csv')

In [3]:
frame.head()

,Timestamp,Open,High,Low,Close,Volume_(BTC),Volume_(Currency),Weighted_Price
0,1499155260,296127,296558,296016,296540,1.158600,3.432441e+05,296257.67168
1,1499155320,296539,296769,296060,296679,11.115510,3.295332e+06,296462.51372
2,1499155380,296060,296090,296060,296060,5.527494,1.636491e+06,296063.83615
3,1499155440,296060,296260,296015,296015,8.414064,2.491620e+06,296125.66780
4,1499155500,296361,296540,296155,296155,3.993010,1.183292e+06,296340.78573

In [4]:
frame.describe()

,Timestamp,Open,High,Low,Close,Volume_(BTC),Volume_(Currency),Weighted_Price
count,5.115750e+05,5.115750e+05,5.115750e+05,5.115750e+05,5.115750e+05,5.115750e+05,5.115750e+05,5.115750e+05
mean,1.514637e+09,8.755354e+05,8.763318e+05,8.747205e+05,8.755351e+05,1.291305e+01,1.163441e+07,8.755078e+05
std,8.942935e+06,4.400117e+05,4.406000e+05,4.394105e+05,4.400085e+05,1.645553e+01,1.696385e+07,4.399933e+05
min,1.499155e+09,2.062910e+05,2.064800e+05,2.060000e+05,2.063460e+05,3.400000e-07,9.952650e-02,2.063754e+05
25%,1.506829e+09,5.000010e+05,5.002700e+05,4.999695e+05,5.000000e+05,3.138781e+00,2.154393e+06,5.000253e+05
50%,1.514710e+09,8.368760e+05,8.374200e+05,8.363910e+05,8.369620e+05,7.603064e+00,5.895066e+06,8.368372e+05
75%,1.522384e+09,1.044120e+06,1.045203e+06,1.043111e+06,1.044130e+06,1.626606e+01,1.416836e+07,1.044122e+06
max,1.530058e+09,2.312098e+06,2.312100e+06,2.300290e+06,2.312098e+06,7.574348e+02,6.936638e+08,2.311319e+06